source 'http://rubygems.org'

# General-use
gem 'elif'

# For slack bot
gem 'slack-ruby-bot'
gem 'celluloid-io'
gem 'activesupport', '~> 5.0'
gem 'json', github: 'flori/json', branch: 'v1.8'
gem 'oj', '~> 2.16.1'

# For site automation
gem 'mechanize'

# Transmission scripts
gem 'transmission-rpc-ruby'

# Systemd notifier
gem 'slack-notifier'
gem 'systemd-journal'
